### ISSUE TITLE
Example doesn't compile

### ISSUE THREAD

**Issue by sporto** [graphql-rust/juniper_rocket#3]
I copy and pasted the example, got errors related to missing `Database`

```
40 |         .manage(Schema::new(Database::new(), EmptyMutation::<Database>::new()))
   |                             ^^^^^^^^ Use of undeclared type or module `Database`
```

It would be great if this repo showed clearer instructions on how to run this example. Or even better provide a complete example that I can then edit to start my project.

Thanks

**Comment by theduke** [comment]
@sporto we just released 0.9.0 and there is also a new book, which contains more guidance.

You can check out the quickstart guide.
Please note though that the book is still very much unfinished, but the quickstart guide is new and the code compiles. ;)

https://graphql-rust.github.io/quickstart.html

If you are still having issues, please open an issue on the main juniper repo.
